# Generated by Django 3.0.8 on 2021-01-31 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infobox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(default='', max_length=255)),
                ('symptoms', models.CharField(default='', max_length=255)),
                ('usual_onset', models.CharField(default='', max_length=255)),
                ('duration', models.CharField(default='', max_length=255)),
                ('types', models.CharField(default='', max_length=255)),
                ('risk_factors', models.CharField(default='', max_length=255)),
                ('complications', models.CharField(default='', max_length=255)),
                ('diagnostic_method', models.CharField(default='', max_length=255)),
                ('prevention', models.CharField(default='', max_length=255)),
                ('treatment', models.CharField(default='', max_length=255)),
                ('medication', models.CharField(default='', max_length=255)),
                ('prognosis', models.CharField(default='', max_length=255)),
                ('frequency', models.CharField(default='', max_length=255)),
                ('deaths', models.CharField(default='', max_length=255)),
                ('icd_code', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='WikiDeath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=255, unique=True)),
                ('frequency', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WikiDiagnosticMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WikiFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=255, unique=True)),
                ('frequency', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WikiMedication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WikiPrevention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WikiRiskFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WikiSymptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WikiTreatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WikiDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
                ('deaths', models.ManyToManyField(to='wiki.WikiDeath')),
                ('diagnostic_methods', models.ManyToManyField(to='wiki.WikiDiagnosticMethod')),
                ('frequency', models.ManyToManyField(to='wiki.WikiFrequency')),
                ('medications', models.ManyToManyField(to='wiki.WikiMedication')),
                ('preventions', models.ManyToManyField(to='wiki.WikiPrevention')),
                ('risk_factors', models.ManyToManyField(to='wiki.WikiRiskFactor')),
                ('symptoms', models.ManyToManyField(to='wiki.WikiSymptom')),
                ('treatments', models.ManyToManyField(to='wiki.WikiTreatment')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=128, unique=True)),
                ('text', models.TextField(default='')),
                ('infobox', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wiki.Infobox')),
            ],
        ),
    ]
