# Generated by Django 3.1.6 on 2021-02-08 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiCaseFatalityRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=255, unique=True)),
                ('frequency', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WikiMortalityRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=255, unique=True)),
                ('frequency', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='wikidisease',
            name='case_fatality_rate',
            field=models.ManyToManyField(to='wiki.WikiMortalityRate'),
        ),
        migrations.AddField(
            model_name='wikidisease',
            name='mortality_rate',
            field=models.ManyToManyField(to='wiki.WikiCaseFatalityRate'),
        ),
    ]
