# Generated by Django 3.0.8 on 2021-02-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikidisease',
            name='specialty',
        ),
        migrations.AddField(
            model_name='wikidisease',
            name='specialty',
            field=models.ManyToManyField(to='wiki.WikiSpecialty'),
        ),
    ]
