# Generated by Django 3.0.8 on 2021-02-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20210228_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikidisease',
            name='icd10',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
