# Generated by Django 3.1.6 on 2021-02-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_auto_20210213_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikidisease',
            name='other_names',
            field=models.TextField(default=''),
        ),
    ]
