# Generated by Django 3.1.6 on 2021-02-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_auto_20210213_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikicasefatalityrate',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='wikideath',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='wikifrequency',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='wikimortalityrate',
            name='frequency',
        ),
        migrations.AddField(
            model_name='wikicasefatalityrate',
            name='frequency_int',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='wikicasefatalityrate',
            name='frequency_ratio',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='wikideath',
            name='frequency_int',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='wikideath',
            name='frequency_ratio',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='wikifrequency',
            name='frequency_int',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='wikifrequency',
            name='frequency_ratio',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='wikimortalityrate',
            name='frequency_int',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='wikimortalityrate',
            name='frequency_ratio',
            field=models.FloatField(null=True),
        ),
    ]
