# Generated by Django 3.1.6 on 2021-02-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_auto_20210214_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikicasefatalityrate',
            name='region_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='wikideath',
            name='region_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='wikifrequency',
            name='region_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='wikimortalityrate',
            name='region_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
