# Generated by Django 3.1.6 on 2021-02-14 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_auto_20210214_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikidisease',
            name='causes',
            field=models.ManyToManyField(to='wiki.WikiCause'),
        ),
    ]
